apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bm145j6ro-nodejs-gitops
  description: This is GitOps manifest for bm145j6ro-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=bm145j6ro-nodejs
    backstage.io/kubernetes-id: bm145j6ro-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: bm145j6ro-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bm145j6ro-nodejs
