apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bm145j6ro-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bm145j6ro-nodejs 
  name: bm145j6ro-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bm145j6ro-nodejs 
